name: al_quran
description: Flutter App for the holy book of Qur'an.
publish_to: none

version: 2.5.6+11

environment:
  sdk: 3.8.1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  # packages
  al_quran_repo:
    path: packages/al_quran_repo
  al_quran_api:
    path: packages/al_quran_api
  
  # utils
  intl: 0.20.2
  share_plus: 11.1.0
  recase: 4.1.0
  shimmer: 3.0.0
  url_strategy: 0.3.0
  cupertino_icons: 1.0.8
  supercharged: 2.1.1

  # network
  dio: 5.8.0+1
  url_launcher: 6.3.2
  
  # state management
  provider: 6.1.5
  equatable: 2.0.7
  flutter_bloc: 9.1.1
  get_it: 8.2.0

  # models generation
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0

  # icon pack
  iconsax: 0.0.8

  # cache
  hive_flutter: 1.1.0
  shared_preferences: 2.5.3

  # app info
  package_info_plus: 8.3.1
  collection: 1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

    # flutter code
  flutter_lints: 6.0.0

  # cache local storage
  build_runner: 2.4.13
  hive_generator: 2.0.1
  
  # misc
  freezed: 2.5.7
  json_serializable: 6.9.0

  # tests
  mocktail: 1.0.4
  bloc_test: 10.0.0
  hive_test: 1.0.1

  # launcher icons
  flutter_launcher_icons: 0.14.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logos/app_icon.png"


# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/logos/
    - assets/intro/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 600
        - asset: fonts/Poppins-Light.ttf
          weight: 200
        - asset: fonts/Poppins-Bold.ttf
          weight: 900
        - asset: fonts/Poppins-Italic.ttf
        - asset: fonts/Poppins-SemiBold.ttf
    - family: Noor
      fonts:
        - asset: fonts/noor-regular.ttf
